# Generated by Django 2.2 on 2020-08-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_type', to='webapp.Article', verbose_name='Задание')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_articles', to='webapp.Type', verbose_name='Тип задачи')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ManyToManyField(related_name='type', through='webapp.ArticleType', to='webapp.Type'),
        ),
    ]
