# Generated by Django 2.2 on 2020-08-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200812_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ManyToManyField(related_name='type', to='webapp.Type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_old',
            field=models.ManyToManyField(related_name='type_set', through='webapp.ArticleType', to='webapp.Type'),
        ),
    ]
