# Generated by Django 2.2 on 2020-08-12 17:03

from django.db import migrations

def transfer_type(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.type.set(article.type_old.all())



def rollback_transfer(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.type_old.set(article.type.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200812_2302'),
    ]

    operations = [
        migrations.RunPython(transfer_type, rollback_transfer)
    ]



