# Generated by Django 2.2 on 2020-08-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200812_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type_old',
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
    ]
