# Generated by Django 2.2 on 2020-08-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200820_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('text', models.TextField(max_length=3000, verbose_name='описание проекта')),
                ('date_start', models.DateTimeField(max_length=25, verbose_name='дата создания')),
                ('date_end', models.DateTimeField(max_length=25, null=True, verbose_name='дата закрытия')),
            ],
        ),
    ]
