# Generated by Django 2.2 on 2020-08-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.Project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
